title: Project Redstoneworld Reborn
author: 
  name: Lenni-Builder and Ijd
  email: ij@theredstoneworld.net

tagline: The official website and info for Project Redstoneworld Reborn!

description:  The official website and info for the Project Redstoneworld Minecraft Map and Server, our Redstone world is one of the largest and longest running of all time, filled with amazing builds, redstone, and command block creations. Made by Ij, TJC, and the Team. Server IP:
mc.theredstoneworld.net or foundingisland.theredstoneworld.net

twitter:
  card: summary_large_image

logo: /android-chrome-512x512.png
#youtube_username: ijdtm7
google_analytics: G-3P18R4FEGC

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

remote_theme: jekyll/minima

#theme: minima

minima:
  skin: solarized-dark
  
  header_pages:
  - j05_about.md
  - j02_discord.md
  - j02_dynmap.md
  - j03_showcase.md
  - j04_helprw.md

  social_links:
  - { platform: youtube,        user_url: "https://www.youtube.com/ijdtm7" }

 
