title: Project Redstoneworld Reborn
author: 
  name: Lenni-Builder and Ijd
  email: ij@theredstoneworld.net

description: >
  The official website and info for Project Redstoneworld Reborn!

twitter:
  card: summary_large_image

logo: https://theredstoneworld.net/android-chrome-512x512.png
#youtube_username: ijdtm7

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

remote_theme: jekyll/minima

#theme: minima

minima:
  skin: solarized-dark
  
  header_pages:
  - j05_about.md
  - j02_discord.md
  - j02_dynmap.md
  - j03_showcase.md
  - j04_helprw.md

  social_links:
  - { platform: youtube,        user_url: "https://www.youtube.com/ijdtm7" }

 
