title: Project Redstoneworld Reborn
url: https://theredstoneworld.net
baseurl: ""
author: 
  name: Site made by Lenni-Builder and Ijd
  email: ij@theredstoneworld.net

tagline: The official website and info for Project Redstoneworld Reborn!

description:  The official website and info for the Project Redstoneworld Minecraft Map and Server, our Redstone world is one of the largest and longest running of all time, filled with amazing builds, redstone, and command block creations. Made by Ij, TJC, and the Team. Server IP at mc.theredstoneworld.net

twitter:
  card: summary_large_image

logo: /android-chrome-512x512.png
#youtube_username: ijdtm7
google_analytics: G-3P18R4FEGC

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap

remote_theme: jekyll/minima@6b9b78d

collections:
  wiki:
    output: true
    permalink: /wiki/:name/

defaults:
  - scope:
      path: ""
      type: wiki
    values:
      layout: wiki
      wiki: true

#theme: minima
header_pages:
  - index.md
  - j02_discord.md
  - j02_dynmap.md
  - j03_showcase.md
  - j04_helprw.md
  - j05_about.md
  - j06_status.md
  - j07_wiki.md

minima:
  skin: solarized-dark
  
  #header_pages:
  #- j02_discord.md
  #- j02_dynmap.md
  #- j03_showcase.md
 # - j04_helprw.md
 # - j07_wiki.md

  social_links:
  - { platform: youtube,        user_url: "https://www.youtube.com/ijdtm7" }

 
